### ISSUE TITLE
Can i modify the code by myself?

### ISSUE THREAD

**Issue by testitabc** [cbrgm/telegram-robot-rss#12]
As I want to add download youtube video function inside the script, after I ran, it will have an operationalerror: attempt to write a readonly database.
So, is it not allow for us to modify the code ?

Sorry about my bad english ..

**Comment by cbrgm** [comment]
Sure, it is allowed to modify the code. Im not exactly sure why this error occures, maybe missing file permissions or something like that?

**Comment by testitabc** [comment]
But after I added the script, it can operates successfully, but those rss can't function anymore..
