### ISSUE TITLE
Support for channels

### ISSUE THREAD

**Issue by AlvesR0** [cbrgm/telegram-robot-rss#24]
Hello. 
The @RobotRssBot work on channels? If it's possible. Are there any restrictions(limit) regarding subscriptions?

Greets,
AlvesR0.

**Comment by cbrgm** [comment]
@AlvesR0 the bot is not designed to be added to channels. It only allows single users to subscribe.

**Comment by JuniorJPDJ** [comment]
This would be very cool addition tho.
