### ISSUE TITLE
Autorun

### ISSUE THREAD

**Issue by vulnz** [cbrgm/telegram-robot-rss#8]
Hello, how can i make autorun of certain rss for all users when they start to talk with bot and make it update after without writing of any commanda. thank you.

**Comment by cbrgm** [comment]
Hi vulnz! Unfortunately it's not possible to do that. The bot is user-driven, so the user has to decide what rss feeds he wants to listen to. The bot will not automatically send messages to users from feeds you defined.

I think what you are looking for is some kind of broadcast bot that is triggered when a new feed is available. Maybe I can add an option for that when hosting the bot yourself or running it inside docker.

**Comment by RBPuneet** [comment]
Hello, I am unable to run Telegram Auto in my system. Any kind of suggestion and help would be highly appreciable.

Please find here the snapshot link: https://www.screencast.com/t/Ub8y8e6cFBlK
